### ISSUE TITLE
Edge Titles / Labels Not Visible

### ISSUE THREAD

**Issue by mepland** [ucsd-ccbb/visJS2jupyter#10]
Hello,

In visJS2jupyter 0.1.8 when hovering over an edge I can not see the title or label. The line does act as it is being highlighted, changing thickness and darkening. I have tried setting `title`, `edge_title_field`, and `edge_label_field` as seen below to no effect.

Is this a known issue? What should I do to display the nodes an edge connects while hovering over it?

Thank you for creating such a useful tool to visualize networks interactively!
```
edges_dict = [{"source":node_map[edges_list[i][0]],
               "target":node_map[edges_list[i][1]],
               "title":"A",
               "edge_title_field":"B",
               "edge_label_field":"C",
               "color":edge_to_color[edges_list[i]] 
              }for i in range(len(edges_list))]

visJS_module.visjs_network(nodes_dict, edges_dict, edge_width=9, tooltip_delay = 0)
```

**Comment by m1webste** [comment]
Sorry for the confusion! Here is some clarification for what the title,  edge_title_field, and edge_label_field parameters do. 

title: this parameter gets modified in your edges_dict (the way your example does it is correct). It is the string you want to be associated with your edge,and is defined on a per-edge basis. So "title" is an attribute associated with each edge.

edge_title_field: this is a parameter of the visjs_network function call. This indicates which edge attribute you want to use as the edge hover text. So you have to name an attribute that you defined in your edges dict ("color", "title", etc.) and not the exact text you want it to display. 

edge_label_field: this is also a parameter of the visjs_network function call. It works exactly like edge_title_field, except that it determines the edge label (the text that is always displayed with an edge) rather than the edge hover text. 


So for example:
edges_dict = [{"source":node_map[edges_list[i][0]],
               "target":node_map[edges_list[i][1]],
               "title":"A",
               "label":"B",
               "color":edge_to_color[edges_list[i]] 
              }for i in range(len(edges_list))]

visJS_module.visjs_network(nodes_dict, edges_dict, "edge_title_field" = "title", "edge_label_field" = "label")

This example should create a graph with each edge labeled as "B". Then when you hover over any edge, "A" should display during the hover. 

Let me know if that solves your problem!
